platform :ios, '8.0'

use_frameworks!

pod 'CameraManager', '~> 2.2'
pod 'Parse'
pod 'Koloda', '~> 3.0.0'
pod 'KYCircularProgress'
pod 'DZNEmptyDataSet'
pod 'Bond'
pod 'ConvenienceKit'
pod 'AFDateHelper'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SwiftGifOrigin'

post_install do |installer|
    `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end



